### ISSUE TITLE
Using accept_statement

### ISSUE THREAD

**Issue by janus** [evincarofautumn/Hap#9]
I was thinking that function body and 'For' body should use accept_statements because of block statements. But I noticed from test that accept_statement worked, could you explain?

shared_ptr<Statement> body(accept_statement(environment));

**Comment by evincarofautumn** [comment]
As in many C-family languages, the grammar of a `for` loop is basically:

```
<for-stat> ::= "for" "(" <stat> ";" <expr> ";" <expr> ")" <stat>
```

So the body of a `for` loop can be a single statement:

```
for (var x = 0; x < 10; x = x + 1)
  trace x;
```

It just happens that one possible statement type is the *block statement*:

```
for (var x = 0; x < 10; x = x + 1) {
  trace x;
  trace (x + 1);
}
```

The same is true for other control flow statement such as `if`, `while`, `when`, and `atomic`.

**Comment by janus** [comment]
It is clear to me after looking at it for second time.
I was thinking that you checked  for accept(Token::LEFT_BRACE) before calling the below. I was indeed I error. Thanks for explaining 
 const auto body(accept_statement(environment));

**Comment by janus** [comment]
Thanks
